### ISSUE TITLE
I HATE YOU

### ISSUE THREAD

**Issue by RatKing51hater** [RatKing51/Bitcoin-Clicker#2]
THIS GAME IS ABSOLUTELY TRASH, WHAT DOES IT TAKE SO LONG TO PROGRESS???????????????????

ok wso when you are need to delete the stupid bbuton that sayu "hundred" by then Bitcoin tcoujnter you need deltebe it because it doesn't make sense because 800 hundred is 800000 yiuostudspid stupid (the auto correct made that readable)

**Comment by RatKing51** [comment]
Who is this?

**Comment by RatKing51** [comment]
Fixed by deleting hundreds
